[toolchain]
channel = "nightly-2026-06-24"
components = ["rustfmt", "miri", "clippy", "rust-src", "llvm-tools"]
# targets = [
#     "riscv64gc-unknown-none-elf",
#     "aarch64-unknown-none",
#     "x86_64-unknown-none",
# ]
profile = "minimal"
