set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(LLDB_BUILD_FRAMEWORK OFF CACHE BOOL "")
set(LLDB_INCLUDE_TESTS OFF CACHE BOOL "")

set(LLVM_TARGETS_TO_BUILD RISCV CACHE STRING "")
set(LLVM_ENABLE_PROJECTS clang;lldb CACHE STRING "")

set(LLDB_ENABLE_PYTHON ON CACHE BOOL "")
set(LLDB_EMBED_PYTHON_HOME OFF CACHE BOOL "")

set(LLVM_BUILD_LLVM_C_DYLIB ON CACHE BOOL "")
set(LLVM_LINK_LLVM_DYLIB ON CACHE BOOL "")

set(LLVM_DISTRIBUTION_COMPONENTS
  lldb
  lldb-python-scripts
  CACHE STRING "")
