[default.extend-words]
sie = "sie"
valu = "valu"
fpr = "fpr"
fle = "fle"
shll = "shll"
endianity = "endianity"   # gimli??
arange = "arange"         # gimli
pre-empted = "pre-empted"
SEH = "SEH"
ands = "ands"
addd = "addd"
ratatui = "ratatui"
datas = "datas"
rela = "rela" # the relocation format

[default.extend-identifier]

[files]
extend-exclude = ["**/emit_tests.rs", "tests/testsuite"]
