load("@prelude//platforms:defs.bzl", "host_configuration")

rust_library(
    name = "fdt",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party:fallible-iterator",
    ],
    visibility = ["PUBLIC"],
    tests = [":fdt_unittests"],
)

rust_test(
    name = "fdt_unittests",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party:fallible-iterator",
    ],
    target_compatible_with = [host_configuration.os, host_configuration.cpu],
    visibility = ["PUBLIC"],
)
