rust_library(
    name = "fdt",
    srcs = glob(["**/*.rs"]),
    deps = [
        "//third-party:fallible-iterator",
    ],
    visibility = ["PUBLIC"],
    tests = [":fdt_unittests"],
)

rust_test(
    name = "fdt_unittests",
    srcs = glob(["**/*.rs"]),
    deps = [
        "//third-party:fallible-iterator",
    ],
    visibility = ["PUBLIC"],
)
