load("@prelude//platforms:defs.bzl", "host_configuration")

rust_library(
    name = "cpu-local",
    srcs = glob(["**/*.rs"]),
    deps = [
        "//lib/util:util",
    ],
    visibility = ["PUBLIC"],
    tests = [":cpu-local_unittests"],
)

rust_test(
    name = "cpu-local_unittests",
    srcs = glob(["**/*.rs"]),
    deps = [
        "//lib/util:util",
    ],
    visibility = ["PUBLIC"],
    target_compatible_with = [host_configuration.cpu, host_configuration.os],
)
