rust_library(
    name = "fastrand",
    srcs = glob(["**/*.rs"]),
    visibility = ["PUBLIC"],
    tests = [":fastrand_unittests"],
)

rust_test(
    name = "fastrand_unittests",
    srcs = glob(["**/*.rs"]),
    visibility = ["PUBLIC"],
)
