rust_library(
    name = "loader-api",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//lib/mem-core:mem-core",
        "//lib/arrayvec:arrayvec",
        "//lib/human-bytes:human-bytes",
    ],
    visibility = ["PUBLIC"],
)
