rust_library(
    name = "panic-unwind",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//lib/unwind:unwind",
        "//lib/cpu-local:cpu-local",
        "//lib/abort:abort",
        "//sys/backtrace:backtrace",
        "//third-party:log",
    ],
    visibility = ["PUBLIC"],
)
