load("@prelude//platforms:defs.bzl", "host_configuration")

rust_library(
    name = "trap",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
    tests = [":trap_unittests"],
)

rust_test(
    name = "trap_unittests",
    srcs = glob(["src/**/*.rs"]),
    target_compatible_with = [host_configuration.os, host_configuration.cpu],
    visibility = ["PUBLIC"],
)
