rust_library(
    name = "sharded-slab",
    srcs = glob(["**/*.rs"]),
    deps = [
        "//lib/spin:spin",
        "//lib/cpu-local:cpu-local",
        "//third-party:log",
    ],
    visibility = ["PUBLIC"],
    tests = [":sharded-slab_unittests"],
)

rust_test(
    name = "sharded-slab_unittests",
    srcs = glob(["**/*.rs"]),
    deps = [
        "//lib/spin:spin",
        "//lib/cpu-local:cpu-local",
        "//third-party:log",
    ],
    visibility = ["PUBLIC"],
)
