name: Build QEMU

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: build QEMU
        run: |
          wget https://download.qemu.org/qemu-9.0.2.tar.xz
          tar xvJf qemu-9.0.2.tar.xz
          cd qemu-9.0.2
          ./configure --target-list="riscv64-softmmu riscv32-softmmu"
          make
      - uses: actions/upload-artifact@v4
        with:
          path: ./build/qemu-system-*
