name: Spelling

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  pre_ci:
    uses: dtolnay/.github/.github/workflows/pre_ci.yml@c385818d09075f9d4c62c66b55ff6ecfe6ca9844 # master

  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Spell Check Repo
        uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b # v1.50.1